# Generated by Django 5.0.2 on 2025-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='premium',
            field=models.BooleanField(default=False, help_text='Premium listings are highlighted and shown first.'),
        ),
    ]
