# Generated by Django 5.0.2 on 2025-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
