# Generated by Django 5.0.2 on 2025-05-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(choices=[('Masvingo-Main Campus', 'Masvingo-Main Campus'), ('Mucheke Campus', 'Mucheke Campus'), ('Masvingo-City Campus', 'Masvingo-City Campus'), ('Mashava Campus', 'Mashava Campus'), ('Harare Campus', 'Harare Campus'), ('Bulawayo Campus', 'Bulawayo Campus'), ('Chiredzi Cohort', 'Chiredzi Cohort')], max_length=100),
        ),
    ]
